const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
let report,stored,reloads=0;const original=(type,props,...children)=>({type,props:{...props,children}});
const R={createElement:original,useState:v=>[v,()=>{}],isValidElement:v=>!!(v&&v.type&&v.props),cloneElement:(v,p)=>({...v,props:{...v.props,...p}})};const N={Text:'Text',View:'View',Pressable:'Pressable',ScrollView:'ScrollView',StyleSheet:{flatten:s=>Array.isArray(s)?Object.assign({},...s):s}};
const revenge={react:{React:R,ReactNative:N},patcher:{instead(p,k,cb){const orig=p[k];p[k]=function(...args){return cb.call(this,args,orig);};return()=>p[k]=orig;}},externals:{ReactNativeClipboard:{Clipboard:{setString:s=>report=s}}}};
const api={plugin:{requireReload(){reloads++;}},jsonStorage:{async get(){return{};},async set(v){stored=v;}}};
const code=fs.readFileSync('plugins/black-cherry/js/index.js','utf8');const opts=vm.runInNewContext('(function(revenge,plugin){return '+code+'\n})(revenge,plugin)',{revenge,plugin:x=>x}).default;
(async()=>{
 await opts.init(api);assert.equal(R.createElement,original,'no early runtime hook');opts.start(api);assert.equal(reloads,0,"normal startup must not request reload");opts.start(api);assert.equal(reloads,0,"repeated start must not request reload");
 const handler=()=>{};const ref={};const props=Object.freeze({style:Object.freeze({borderRadius:24}),onLayout:handler,onResponderRelease:handler,ref,channelId:'PRIVATE'});
 const composer=R.createElement('RCTView',props);assert.equal(composer.props.style[1].backgroundColor,'#260912');assert.equal(composer.props.onLayout,handler);assert.equal(composer.props.ref,ref);assert.equal(props.style.borderWidth,undefined);
 const named=R.createElement('FloatingChatInputContainer',{style:{borderWidth:0}});assert.equal(named.props.style[1].borderColor,'#a63455');
 const headerProps=Object.freeze({hidden:true,style:Object.freeze({height:56}),title:'PRIVATE',ref,onLayout:handler});
 const header=R.createElement('RNSScreenStackHeaderConfig',headerProps);
 assert.equal(header.props.titleColor,'#f8e6e9');assert.equal(header.props.style[1].backgroundColor,'#210610');
 assert.equal(header.props.hidden,true);assert.equal(header.props.ref,ref);assert.equal(header.props.onLayout,handler);
 assert.equal(headerProps.style.backgroundColor,undefined);
 const customStyle=Object.freeze({height:56,flexDirection:'row',backgroundColor:'#19191c'});
 assert.equal(R.createElement('CustomDMHeader',{style:customStyle,title:'PRIVATE'}).props.style,customStyle,'unknown header observed only');
 R.createElement('CustomDMHeader',{style:customStyle,title:'PRIVATE'});
 assert.equal(R.createElement('View',{style:customStyle}).props.style,customStyle,'candidate row observed only');
 const backingProps=Object.freeze({style:customStyle,nativeID:'PRIVATE',shouldRasterizeIOS:false,hasEnteringAnimation:false,forwardedRef:ref,ref,collapsable:false});
 assert.equal(R.createElement('ReanimatedView',backingProps).props.style,customStyle,'old global heuristic removed');
 const inner=Object.freeze({type:'View',key:'inner',ref,props:Object.freeze({style:customStyle,onPress:handler,ref,children:'PRIVATE'})});
 const tree=Object.freeze({type:'View',key:'root',ref,props:Object.freeze({style:customStyle,onLayout:handler,children:inner})});
 function NavigationHeader(props){assert.equal(props.channel,'PRIVATE');R.useState(1);return tree;}
 const wrapped=R.createElement(NavigationHeader,{channel:'PRIVATE'});
 assert.notEqual(wrapped.type,NavigationHeader);
 assert.equal(R.createElement(NavigationHeader,{channel:'PRIVATE'}).type,wrapped.type,'stable component identity');
 const rendered=wrapped.type(wrapped.props);
 assert.equal(rendered.props.style[1].backgroundColor,'#210610');assert.equal(rendered.key,'root');assert.equal(rendered.ref,ref);
 assert.equal(rendered.props.onLayout,handler);assert.equal(rendered.props.children.props.onPress,handler);
 assert.equal(rendered.props.children.props.style[1].backgroundColor,'#210610');
 assert.equal(tree.props.style,customStyle);assert.equal(inner.props.style,customStyle);
 const tracking=Object.freeze({span:'PRIVATE'});
 const backingTree=Object.freeze({type:'NavTTIView',key:'backing',ref,props:Object.freeze({style:customStyle,tracking,spanComponent:'PRIVATE',children:'PRIVATE'})});
 const fragmentTree=Object.freeze({type:'Fragment',props:Object.freeze({children:[backingTree]})});
 function Header(){return fragmentTree;}
 const channelHeader=R.createElement(Header,{channelId:'PRIVATE',frame:{}});
 const headerResult=channelHeader.type(channelHeader.props).props.children[0];
 assert.equal(headerResult.props.style[1].backgroundColor,'#210610');
 assert.equal(headerResult.props.tracking,tracking);assert.equal(headerResult.props.spanComponent,'PRIVATE');
 assert.equal(headerResult.props.children,'PRIVATE');assert.equal(headerResult.key,'backing');assert.equal(headerResult.ref,ref);
 assert.equal(backingTree.props.style,customStyle,'tracking wrapper style immutable');
 assert.equal(R.createElement('NavTTIView',backingTree.props).props.style,customStyle,'no global tracking-view tint');
 assert.equal(R.createElement(Header,{}).type,Header,'non-channel Header untouched');
 function UnrelatedHeader(){return tree;}
 assert.equal(R.createElement(UnrelatedHeader,{}).type,UnrelatedHeader,'unrelated component untouched');
 assert.equal(R.createElement('DCDChatInput',{placeholder:'PRIVATE'}).props.textColor,'#f8e6e9');
 const avatarStyle={backgroundColor:'#23a55a',borderRadius:24,width:48,height:48};assert.equal(R.createElement('View',{style:avatarStyle}).props.style,avatarStyle,'avatars and status untouched');
 const messageStyle={color:'#ffffff'};assert.equal(R.createElement('Text',{style:messageStyle}).props.style,messageStyle);
 const children=opts.SettingsComponent().props.children;const buttons=children.filter(c=>c.type==='Pressable');buttons[1].props.onPress();assert.ok(!report.includes('PRIVATE'),'reports exclude user field values');assert.equal(JSON.parse(report).composers,2);
 const diagnostics=JSON.parse(report);assert.equal(diagnostics.version,'0.1.5');assert.equal(diagnostics.customHeaders,3);assert.equal(diagnostics.headerBackings,1);
 assert.equal(diagnostics.headerSamples.find(s=>s.component==='RNSScreenStackHeaderConfig').hidden,true);
 assert.equal(diagnostics.headerSamples.find(s=>s.component==='CustomDMHeader').renders,2);
 assert.ok(diagnostics.headerSamples.some(s=>s.kind==='row-candidate'));
 for(let i=0;i<100;i++)R.createElement('CustomHeader'+i,{title:'PRIVATE'});
 buttons[1].props.onPress();assert.equal(JSON.parse(report).headerSamples.length,60,'bounded header report');assert.ok(!report.includes('PRIVATE'));
 await buttons[0].props.onPress();assert.equal(stored.tintChat,false);assert.equal(R.createElement('DCDChat',{style:avatarStyle}).props.style,avatarStyle);
 opts.stop(api);assert.equal(wrapped.type(wrapped.props),tree,'mounted adapter becomes inert after disabling');assert.equal(R.createElement,original);assert.equal(reloads,2,"only settings and disabling request reload");
 api.plugin.startedLate=true;await opts.init(api);opts.start(api);assert.equal(reloads,2,"late startup must not request reload either");opts.stop(api);assert.equal(R.createElement,original);console.log('PASS: loader, late hooks, immutable native props, touch/ref preservation, scope, privacy, settings and cleanup');
})().catch(e=>{console.error(e);process.exitCode=1;});
