from pathlib import Path
import base64
root=Path(__file__).resolve().parent.parent
styles=['mercury','prism','afterimage','jellyfish']
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Shine + Motion previews</title><style>
*{box-sizing:border-box}body{margin:0;background:#070911;color:#eef2ff;font:15px system-ui;padding:36px}main{max-width:1050px;margin:auto}h1{font-size:36px;margin:0}p{color:#a7aec2;line-height:1.6}.controls{display:flex;gap:12px;margin:20px 0 30px}button{background:#191e2e;border:1px solid #444b62;color:#eef2ff;padding:12px 20px;border-radius:14px;cursor:pointer}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:20px}.phone{height:480px;position:relative;overflow:hidden;border:1px solid #3e4453;border-radius:26px;background:#070911}.art{position:absolute;inset:-24px -16px;background-position:center;background-size:cover;animation:drift 22s ease-in-out infinite alternate;pointer-events:none;opacity:.72}.prism .art{animation-duration:17s}.afterimage .art{animation:trail 8s ease-in-out infinite alternate}.jellyfish .art{animation:float 24s ease-in-out infinite alternate}.ui{position:relative;height:100%;background:rgba(7,9,17,.18);padding:18px 12px;display:flex;flex-direction:column}.header{padding:12px;border-radius:14px;background:rgba(17,21,35,.6);border:1px solid #393e4c;font-weight:600}.message{display:flex;gap:8px;margin-top:30px;font-size:12px}.avatar{width:24px;height:24px;flex-shrink:0;background:#9886c7;border-radius:50%}.message:nth-child(odd) .avatar{background:#659cab}.message b{display:block;margin-bottom:7px}.message span{color:#c0c6d7;line-height:1.6}.input{margin-top:auto;padding:12px;background:rgba(17,21,35,.75);border:1px solid #3e4453;border-radius:14px;color:#adb6c9;font-size:12px}h2{font-size:19px}.paused .art{animation-play-state:paused}.static .art{animation:none}.fast .art{animation-duration:8s}@keyframes drift{to{transform:translateY(8px) scale(1.05);opacity:1}}@keyframes trail{to{transform:translateY(18px) scale(1.025);opacity:1}}@keyframes float{to{transform:translateY(-16px) scale(1.025);opacity:1}}@media(max-width:800px){.grid{grid-template-columns:repeat(2,1fr)}}@media(prefers-reduced-motion:reduce){.art{animation:none!important}}@media(max-width:430px){body{padding:20px}.grid{grid-template-columns:1fr}.phone{max-width:300px;margin:auto}}
</style><main><h1>Shine + Motion</h1><p>Four animated material studies using the plugin’s bundled artwork. Illustrative chat layout; actual Revenge screens keep Discord’s native layout.</p><div class="controls"><button id="pause">Pause motion</button><button id="speed">Speed: slow</button></div><div class="grid">'''
for style in styles:
    uri='data:image/jpeg;base64,'+base64.b64encode((root/'assets/shine-motion'/f'{style}.jpg').read_bytes()).decode()
    html+=f'<section><h2>{style.title()}</h2><div class="phone {style}"><div class="art" style="background-image:url({uri})"></div><div class="ui"><div class="header">‹ &nbsp; Messages &nbsp; ⌕</div>'
    for who,msg in [('kittenk','this looks unreal'),('kev','the reflections move?'),('kittenk','yeah, slowly ✧'),('kev','clean. keep it.')]:html+=f'<div class="message"><div class="avatar"></div><div><b>{who}</b><span>{msg}</span></div></div>'
    html+='<div class="input">＋ &nbsp; Message…</div></div></div></section>'
html+='''</div><p>Chrome reflection · spectral rims · neon trails · bioluminescent bells. Reduced motion is respected automatically. Plugin settings also let you change glass opacity.</p></main><script>document.getElementById('pause').onclick=function(){document.body.classList.toggle('paused');this.textContent=document.body.classList.contains('paused')?'Resume motion':'Pause motion'};document.getElementById('speed').onclick=function(){document.body.classList.toggle('fast');this.textContent=document.body.classList.contains('fast')?'Speed: normal':'Speed: slow'};</script></html>'''
(root/'assets/shine-motion/preview.html').write_text(html)
